server:
  port: 13000
  servlet:
    context-path: /system

spring:
  datasource:
    url: jjdbc:mysql://127.0.0.1:3306/lws?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

## mybatis mapper文件位置指定
mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.lws.system.entity
  #逻辑删除统一配置
  global-config:
    db-config:
      logic-delete-field: deleteFlag  #全局逻辑删除字段值
      logic-delete-value: 0 # 逻辑已删除值(默认为 0)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 1)