spring:
  application:
    name: eureka-server-2.x
# 帐号密码支持
#  security:
#    user:
#      name: abc
#      password: abc
server:
  port: 8762
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    hostname: localhost
  client:
    # 注册自己
    register-with-eureka: true
    # 是否同步其他eureka的列表数据（集群设置true）
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
# 帐号密码支持
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka
